import os

SECRET_KEY = os.getenv("ACCESS_SECRET_KEY", "DemoAppSecretKey")
ID_SECRET_KEY = os.getenv("ID_SECRET_KEY", "DemoAppIDSecretKey")
ALGORITHM = "HS256"
AUTH_SESSION = 10
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_HOURS = 24
